name: Docker guacamole-server Build

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

jobs:
  guacamole_server:
    name: Docker guacamole-server Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Private Actions Checkout
        uses: actions/checkout@v5
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.11.1
      -
        name: Get resources
        run: |
          rm -rf *
          wget -O /tmp/master.zip https://github.com/apache/guacamole-server/archive/refs/heads/master.zip
          unzip /tmp/master.zip -d /tmp
          mv /tmp/guacamole-server-master/* .
      -
        name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/arm64,linux/amd64
#           file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/guacd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/guacd:1.3.0
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/guacd:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/guacd:cache,mode=max
      -
        name: Send notification to Feishu
        uses: XRSec/feishu-bot-webhook-action@v1
        with:
          FEISHU_BOT_WEBHOOK: ${{ secrets.FEISHU_BOT_WEBHOOK }}
          FEISHU_BOT_SIGNKEY: ${{ secrets.FEISHU_BOT_SIGNKEY }}

  Repository_Dispatch:
    needs: guacamole_server
    runs-on: ubuntu-latest
    steps:
      -
        name: Private Actions Checkout
        uses: actions/checkout@v5
      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/guacd
